name = "PhysicalConstants"
uuid = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
authors = ["Mos√® Giordano <mose@gnu.org>"]
version = "0.1.0"

[deps]
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
